### ISSUE TITLE
FocalLossForwardGPU has unrecognized token

### ISSUE THREAD

**Issue by cocorecoco** [sciencefans/Focal-Loss#1]
I found unrecognized token in gpu file: 

`oriloss[ i ] = - £¨input_data[ i ] * ( target[ i ] - ( input_data[ i ] >= 0 ) ) -

				log(1 + exp(input_data[ i ] - 2 * input_data[ i ] *

				( input_data[ i ] >= 0 )))£©;`

**Comment by liuyuisanai** [comment]
Thanks for your feed back! This issue is caused by VS2013 editor and might cause compile error for Linux users. I've just fixed it, pls check again.

**Comment by cocorecoco** [comment]
OK
