### ISSUE TITLE
Some question about the focal_loss_layer.cpp

### ISSUE THREAD

**Issue by 408550969** [sciencefans/Focal-Loss#13]
Hi
I find the  focal_loss_layer.cpp is similar with sigmoid_cross_entropy_loss_layer.cpp.
The only difference is that you define the  num = bottom[0]->num() , and the  top[0]->mutable_cpu_data()[0] = loss / num ,instead of top[0]->mutable_cpu_data()[0] = loss/normalizer_ .
May I ask what's the meaning of the num,and where is the focal-loss?
Thanks

**Comment by liuyuisanai** [comment]
I didn't implement cpu version, pls refer to .cu
