### ISSUE TITLE
softmax based version for multiclass case

### ISSUE THREAD

**Issue by cocorecoco** [sciencefans/Focal-Loss#2]
Have you planed implementing an softmax-based version for multiclass case?

**Comment by liuyuisanai** [comment]
Not yet. However you can easily implement that by combining the second item in my code to softmaxLoss layer.

**Comment by zimenglan-sysu-512** [comment]
hi @cocorecoco,

you can see my implementation using softmax function. https://github.com/zimenglan-sysu-512/Focal-Loss

**Comment by liuyuisanai** [comment]
@zimenglan-sysu-512 Thanks for your implementation! I'll ref your code in my readme.

**Comment by zimenglan-sysu-512** [comment]
hi @sciencefans,

thanks for your kindness. can u give more details about how u implement the `bp`? your code is optimized for speed, but look more complicated.

thanks again.

**Comment by liuyuisanai** [comment]
@zimenglan-sysu-512 Please refer to [issue#3](https://github.com/sciencefans/Focal-Loss/issues/3) for my inference.

**Comment by zimenglan-sysu-512** [comment]
hi @sciencefans,

i am confused by `d(scaler)`. 
so can u show it more simply in details?

thanks.
