### ISSUE TITLE
Can you provide evaluate result on coco as the paper shows? 

### ISSUE THREAD

**Issue by DuinoDu** [sciencefans/Focal-Loss#5]
Rt

**Comment by liuyuisanai** [comment]
Sorry, we've now just evaluated it on face detection task and object proposal detection task with about 2% gain, but not on overall object detection task.

**Comment by XiongweiWu** [comment]
@sciencefans hi, can u share your parameters which contributes to improve your framework?I find focal loss is quite sensitive to alpha and gamma

**Comment by ujsyehao** [comment]
@XiongweiWu Does focal loss has alpha param?
